name: Release
on:
  push:
    branches:
      - main
      - next
      - alpha
      - beta
      - "*.x"
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build
        run: docker build --tag mcmanning/mumble-summary-cards .

      - name: Release
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
